modLoader = "javafml" #mandatory
loaderVersion = "[4,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "MIT"

[[mods]] #mandatory
modId = "create_radar" #mandatory
version = "0.4" #mandatory
displayName = "Create: Radars" #mandatory
authors = "HappySG, CeoOfGoogle, Kipti, OndatraCZE, Ray(furuochen)" #optional

# The description text for the radar (multi line!) (#mandatory)
description = '''Welcome to Create Radars, a mod offering a variety of tools and blocks for Surveillance, Detection, and Controlling Weapons.'''

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.create_radar]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.create_radar]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"
[[dependencies.create_radar]]
modId = "create"
type = "required"
versionRange = "[6.0.8,6.1.0)"
ordering = "BEFORE"
side = "BOTH"
[[dependencies.create_radar]]
modId = "createbigcannons"
type = "optional"
versionRange = "[5.11.0,)"
ordering = "BEFORE"
side = "BOTH"
[[dependencies.create_radar]]
modId = "valkyrienskies"
type = "optional"
versionRange = "[2.4.7,)"
ordering = "BEFORE"
side = "BOTH"
[[dependencies.create_radar]]
modId="shupapium"
type = "optional"
versionRange="[1.0,2.0)"
ordering="BEFORE"
side="BOTH"
