modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "create_radar"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[mixins]]
config = "create_radar.mixins.json"

[[dependencies.create_radar]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.create_radar]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.create_radar]]
modId = "create"
type = "required"
versionRange = "[6.0.10,6.1.0)"
ordering = "NONE"
side = "BOTH"

[[dependencies.create_radar]]
modId = "createbigcannons"
type = "required"
versionRange = "[5.11.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.create_radar]]
modId = "valkyrienskies"
type = "optional"
versionRange = "[2.4.7,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.create_radar]]
modId = "shupapium"
type = "optional"
versionRange = "[1.0,2.0)"
ordering = "NONE"
side = "BOTH"

[[dependencies.create_radar]]
modId = "computercraft"
type = "optional"
versionRange = "[1.113.0,2.0)"
ordering = "AFTER"
side = "BOTH"
